version: '3'
services:
  user-management-service:
    build:
      context: ./user-management-service
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./user-management-service:/app
  user-management-db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
    - user-management-data:/var/lib/postgresql/data

volumes:
 user-management-data: